---
- hosts: all
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t devops-project:latest .
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag devops-project devopsnike/devops-project

    - name: push image on to dockerhub
      command: docker push devopsnike/devops-project

    - name: remove docker images from ansible server
      command: docker image rm tomcat devopsnike/devops-project devops-project
      ignore_errors: yes
