---
- hosts: demo[1]
  user: ansible
  become: yes

  tasks:

    - name: stop current running container
      command: docker container stop $(docker ps -aq)
      ignore_errors: yes

    - name: remove stopped docker container
      command: docker container rm $(docker ps -aq)
      ignore_errors: yes

    - name: remove current docker image
      command: docker image prune -f
      ignore_errors: yes

    - name: pull docker image from dockerhub
      command: docker pull devopsnike/devops-project:latest

    - name: creating docker container using devopsnike/devops-project image
      command: docker run -d --name project -p 8080:8080 devopsnike/devops-project:latest
