---
- hosts: demo[0]
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t devopsnike/devops-project .
      args:
        chdir: /opt/docker

    - name: push image on to dockerhub
      command: docker push devopsnike/devops-project

    - name: remove docker images from ansible server
      command: docker image rm tomcat devopsnike/devops-project devops-project
      ignore_errors: yes
